import { AUTO, DESKTOP, MOBILE } from "./string.constants";

const WORDS = [
  "Algorithm",
  "Binary",
  "Cache",
  "Compiler",
  "Encryption",
  "Firewall",
  "Hacker",
  "RAM",
  "Registry",
  "Virus",
  "Search engine",
  "Google Maps",
  "Google Translate",
  "YouTube",
  "Google Drive",
  "Chrome browser",
  "Gmail",
  "Android OS",
  "Google Assistant",
  "Google Classroom",
  "Windows OS",
  "Office Suite",
  "Xbox",
  "Visual Studio",
  "Azure",
  "Microsoft Teams",
  "Skype",
  "Edge browser",
  "Surface devices",
  "Power BI",
  "Android Studio",
  "Kotlin programming language",
  "Material Design",
  "Android NDK",
  "Android SDK",
  "Google Play Store",
  "Android Emulator",
  "Android Debug Bridge (ADB)",
  "Android App Bundle",
  "Jetpack Compose",
  "Climate change",
  "Fossil fuels",
  "Renewable energy",
  "Global warming",
  "Tectonic plates",
  "Greenhouse gases",
  "Ecosystems",
  "Air pollution",
  "Water pollution",
  "Natural disasters",
  "Quantum mechanics",
  "Relativity",
  "Thermodynamics",
  "Electromagnetism",
  "Particle physics",
  "Optics",
  "Astrophysics",
  "Nuclear physics",
  "Magnetism",
  "Gravity",
  "Periodic table",
  "Chemical reactions",
  "Acids and bases",
  "Organic chemistry",
  "Thermochemistry",
  "Analytical chemistry",
  "Inorganic chemistry",
  "Biochemistry",
  "Nanotechnology",
  "Materials science",
  "Cell biology",
  "Genetics",
  "Evolution",
  "Ecology",
  "Microbiology",
  "Anatomy",
  "Physiology",
  "Immunology",
  "Neuroscience",
  "Biotechnology",
  "Football (Soccer)",
  "Basketball",
  "Tennis",
  "Cricket",
  "Baseball",
  "Volleyball",
  "Golf",
  "Swimming",
  "Athletics",
  "Boxing",
  // Sports
  "athletics",
  "baseball",
  "basketball",
  "boxing",
  "championship",
  "cricket",
  "cycling",
  "football",
  "gymnastics",
  "hockey",
  "karate",
  "medal",
  "olympics",
  "paddleboarding",
  "quidditch",
  "rugby",
  "skiing",
  "swimming",
  "tennis",

  // BTC/Crypto
  "altcoin",
  "blockchain",
  "cold wallet",
  "cryptocurrency",
  "decentralized",
  "digital wallet",
  "exchange",
  "hashrate",
  "ledger",
  "mining",
  "node",
  "proof of work",
  "satoshi",
  "smart contract",
  "token",
  "wallet",
  "whale",
  "whitepaper",

  // Weather
  "blizzard",
  "climate",
  "cyclone",
  "drizzle",
  "flood",
  "forecast",
  "heatwave",
  "hurricane",
  "lightning",
  "monsoon",
  "precipitation",
  "rainbow",
  "sleet",
  "storm",
  "tornado",
  "typhoon",
  "windchill",
  "winter",
  "thunderstorm",

  // English word meanings
  "aberration",
  "bewilderment",
  "circumvent",
  "deprecate",
  "eloquent",
  "frivolous",
  "gullible",
  "histrionic",
  "indomitable",
  "juxtapose",
  "kinetic",
  "luminous",
  "malinger",
  "nefarious",
  "obfuscate",
  "panacea",
  "quintessential",

  // Questions
  "What is the highest grossing sport in the world?",
  "How does cryptocurrency mining work?",
  "What is the difference between a hurricane and a typhoon?",
  "What is the meaning of the word 'aberration'?",
  "What is the 'static' keyword used for in Java?",
  "What is venture capital funding?",
  "How does the education system differ in different countries?",
  "What is the purpose of a board of directors?",

  // E-commerce
  "affiliate marketing",
  "cart abandonment",
  "digital marketing",
  "dropshipping",
  "e-commerce platform",
  "fulfillment",
  "inventory management",
  "payment gateway",
  "product listing",
  "shipping",
  "shopping cart",
  "supply chain",

  // Flutter
  "animation",
  "app development",
  "cross-platform",
  "debugging",
  "hot reload",

  // Other Trending Topics
  "artificial intelligence",
  "augmented reality",
  "blockchain technology",
  "cloud computing",
  "cybersecurity",
  "data analytics",
  "digital transformation",
  "machine learning",
  "quantum computing",
  "virtual reality",

  // Crypto Trading
  "altcoin",
  "arbitrage",
  "bear market",
  "bull market",
  "candlestick",
  "crypto exchange",
  "decentralized finance",
  "exchange rate",
  "FOMO",
  "HODL",
  "ICO",
  "limit order",
  "market cap",
  "order book",
  "pump and dump",
  "short selling",
  "stop loss",
  "technical analysis",
  "wallet",

  // Money Making
  "affiliate marketing",
  "passive income",
  "freelancing",
  "e-commerce",
  "dropshipping",
  "investing",
  "real estate",
  "network marketing",
  "online courses",
  "stock market",
  "rental properties",
  "side hustles",
  "blogging",
  "podcasting",
  "selling digital products",
  "selling physical products",
  "social media marketing",
  "web development",

  // Questions on Money Making
  "How can I make money online?",
  "What are some good passive income ideas?",
  "What is affiliate marketing?",
  "How can I start investing?",
  "How can I make money from blogging?",
  "What are some side hustles I can do?",
  "What are some ways to make money from home?",
  "How much money do I need to start investing in the stock market?",

  // Questions to Get Help from Computer Services
  "How do I reset my password?",
  "How can I fix my slow computer?",
  "How can I remove a virus from my computer?",
  "What should I do if I can't connect to the internet?",
  "How can I backup my files?",
  "How can I update my software?",
  "How can I connect my printer to my computer?",
  "How can I recover a deleted file?",

  // Programming
  "algorithm",
  "API",
  "coding",
  "database",
  "debugging",
  "frontend development",
  "backend development",
  "data structures",
  "functional programming",
  "IDE",
  "OOP",
  "test-driven development",
  "version control",
  "web development",
  "XML",
  "REST API",
  "JSON",
  "SOAP",
  "CI/CD",
];

const SEARCH_MODES: string[] = [MOBILE, DESKTOP, AUTO];

const DEVICE_TYPES: string[] = [MOBILE, DESKTOP];
export { WORDS, SEARCH_MODES, DEVICE_TYPES };
